### PR TITLE
Dummy change in README.md

### PR DESCRIPTION
**Pull request by javihernandez**
CI test

### CODE REVIEW

**Comment by kaspermarkus** [comment]
Woooohooooo

**Comment by javihernandez** [comment]
> Woooohooooo

look at the end of this log https://ci.gpii.net/job/create-gpii-app-vm/41/consoleFull

<pre>
==> default:   'heat' is not recognized as an internal or external command,
==> default:   operable program or batch file.
==> default: C:\installer\setup\setup.msbuild(50,5): error MSB3073: The command "heat dir "..\temp\GPII" -dr INSTALLFOLDER -ke -srd -cg GPII -var var.publishDir -gg -out "..\temp\GPII.wxs"" exited with code 9009.
==> default: Done Building Project "C:\installer\setup\setup.msbuild" (default targets) -- FAILED.
==> default: 
==> default: Build FAILED.
==> default: 
==> default: "C:\installer\setup\setup.msbuild" (default target) (1) ->
==> default: (GPII target) -> 
==> default:   C:\installer\setup\setup.msbuild(50,5): error MSB3073: The command "heat dir "..\temp\GPII" -dr INSTALLFOLDER -ke -srd -cg GPII -var var.publishDir -gg -out "..\temp\GPII.wxs"" exited with code 9009.
==> default: 
==> default:     0 Warning(s)
==> default:     1 Error(s)
==> default: 
==> default: Time Elapsed 00:00:32.90
==> default: VERBOSE: 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild.exe' exited with 1
==> default: Installation process returned error code: 1
==> default: 
==> default: At C:\vagrant\provisioning\Provisioning.psm1:44 char:5
==> default: +     throw "Installation process returned error code: $($exitCode)"
==> default: +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> default:     + CategoryInfo          : OperationStopped: (Installation pr...d error code: 1:String) [], RuntimeException
==> default:     + FullyQualifiedErrorId : Installation process returned error code: 1
==> default:  
Finished: SUCCESS
</pre>

So, the installer doesn't build and ci takes it as "SUCCESS" :tada:

**Comment by gloob** [comment]
It looks like we are not adding the wix folder to the path or not refreshing the environment vars accordingly.

**Comment by stegru** [comment]
You might want to do a [`set -e` equivalent](https://stackoverflow.com/questions/9948517/how-to-stop-a-powershell-script-on-the-first-error) in the build script, or `exit $LastExitCode`.

**Comment by javihernandez** [comment]
Ok, I've updated the Vagrantfile to use the most recent windows box and now the failure has been reported in CI. Nice! Sooooo ... let's sweep this problem under the rug. I guess that we can take care of it by applying @stegru's recommendations if this rears its fat ugly head again in the future.
wrt the installer not being built, as @gloob said, the problem is related to wix and its path. It turns out that there's a new version of wixtoolset in chocolatey (hence the change in the wix path), and the path is being hardcoded [here](https://github.com/GPII/windows/blob/hst-2017/provisioning/Chocolatey.ps1#L35) and that's why we can't call to heat.exe. I've documented the problem in this [JIRA ticket](https://issues.gpii.net/browse/GPII-2438)

**Pull request closed without merging**
