### PR TITLE
CI test: feature/qss+build fix

### PR DESCRIPTION
**Pull request by javihernandez**
This is supposed to be merged into @danailbd's feature/QSS branch but I'm passing it through CI before submitting it.

### CODE REVIEW

**Comment by javihernandez** [comment]
```
npm ERR! code EINTEGRITY
npm ERR! sha1-0Ng2s0OqbbiMDez+rnHmJ11BQg4= integrity checksum failed when using sha1: wanted sha1-0Ng2s0OqbbiMDez+rnHmJ11BQg4= but got sha1-LDikuaiNgLd9TCnjALxAD6FkG3w=. (8633078 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vagrant\AppData\Roaming\npm-cache\_logs\2018-08-01T14_27_37_981Z-debug.log
Installation process returned error code: 1
At C:\vagrant\provisioning\Provisioning.psm1:44 char:5
+     throw "Installation process returned error code: $($exitCode)"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Installation pr...d error code: 1:String) [], RuntimeException
    + FullyQualifiedErrorId : Installation process returned error code: 1

```
ok to test

**Comment by javihernandez** [comment]
ok to test

**Comment by javihernandez** [comment]
ok to test

**Comment by amb26** [comment]
Closed for https://github.com/GPII/gpii-app/pull/60 as the new "CI pass du jour"

**Pull request closed without merging**
