### PR TITLE
GPII-3810: Updated to corresponding version of gpii-windows

### PR DESCRIPTION
**Pull request by javihernandez**

### CODE REVIEW

**Comment by javihernandez** [comment]
passing locally ... ok to test

**Comment by javihernandez** [comment]
> CI job failed: https://ci.gpii.net/job/gpii-app-tests/944/

timed out during vm creation - the installer creation was nearly finished.

**Comment by javihernandez** [comment]
ok to test

**Comment by Karadaliev** [comment]
@javihernandez we have a conflict here 🛩️

**Comment by amb26** [comment]
Screen mirroring has been axed, this pull can be closed

**Comment by javihernandez** [comment]
> Screen mirroring has been axed, this pull can be closed

Right, this was an old update to gpii-windows and gpii-app is already in sync with a more recent version of gpii-windows

**Pull request closed without merging**
