### PR TITLE
Testing crash fix

### PR DESCRIPTION
**Pull request by stegru**
:warning: Just a test harness, don't merge.

### CODE REVIEW

**Comment by stegru** [comment]
ok to test

**Comment by javihernandez** [comment]
> CI job passed: https://ci.gpii.net/job/gpii-app-tests/466/

@stegru does this means "victory"?

**Comment by stegru** [comment]
Almost. Let's see if it passes on https://github.com/GPII/gpii-app/pull/67

However, I've just had a different fail in https://github.com/GPII/gpii-app/pull/70, which points to the same gpii-windows branch.

**Comment by amb26** [comment]
Looks dead

**Pull request closed without merging**
