### PR TITLE
GPII-4042: Word Simplification don't have a working [changed] indicator

### PR DESCRIPTION
**Pull request by krisYanachkov**
Added button presenter to "MS Word Simplify" widget.

### CODE REVIEW

**Comment by Karadaliev** [comment]
@javihernandez @amb26 Ready for review ;-)

**Comment by javihernandez** [comment]
ok to test

**Comment by javihernandez** [comment]
@Karadaliev hey there,
I've been testing this and it actually shows the "changed" indicator when tweaked. However, when I reset to standard, the indicator remains there. Can you take a look at this?

**Comment by krisYanachkov** [comment]
> @Karadaliev hey there,
> I've been testing this and it actually shows the "changed" indicator when tweaked. However, when I reset to standard, the indicator remains there. Can you take a look at this?

@javihernandez I think this is because the new reset to standard logic is not merged in this branch.

**Pull request merged**
