### PR TITLE
GPII-3958: Combining cindyli's API fix with vernandez' installer fix

### PR DESCRIPTION
**Pull request by amb26**

### CODE REVIEW

**Comment by amb26** [comment]
Our standard race condition:
````
03:45:38.035:  jq: FAIL: Module "gpii.tests.dev.config tests" Test name "GPII application dev config integration tests" - Message: Tray tooltip label - at sequence position 7 of 16
03:45:38.035:  jq: Expected: Morphic: User Signed In
03:45:38.035:  jq: Actual: Morphic: Ready
````

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
Makes absolutely no sense. The changes have affected nothing at the binary level, yet we are somehow magically unable to load ref-napi

**Comment by javihernandez** [comment]
ok to test

**Comment by amb26** [comment]
Failure: 
````
14:13:44.275:  FATAL ERROR: Uncaught exception: The specified module could not be found.
\\?\UNC\vboxsvr\vagrant\node_modules\gpii-windows\gpii-service\node_modules\ref-napi\build\Release\binding.node
Error: The specified module could not be found.
\\?\UNC\vboxsvr\vagrant\node_modules\gpii-windows\gpii-service\node_modules\ref-napi\build\Release\binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (\\vboxsvr\vagrant\node_modules\gpii-windows\gpii-service\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (\\vboxsvr\vagrant\node_modules\gpii-windows\gpii-service\node_modules\ref-napi\lib\ref.js:7:47)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (\\vboxsvr\vagrant\node_modules\gpii-windows\gpii-service\src\windows.js:20:11
````

**Comment by amb26** [comment]
ok to test

**Pull request merged**
