### PR TITLE
GPII-3438: Update to electron 3.0.2

### PR DESCRIPTION
**Pull request by javihernandez**

### CODE REVIEW

**Comment by amb26** [comment]
ok to test

**Comment by javihernandez** [comment]
ok to test

**Comment by javihernandez** [comment]
> CI job failed: https://ci.gpii.net/job/gpii-app-tests/433/

```
nodejs.install not installed. An error occurred during installation:
 The remote server returned an error: (503) Server Unavailable. Service Unavailable
```
ok to test

**Comment by javihernandez** [comment]
ok to test

**Pull request merged**
