### PR TITLE
GPII-3786: Fix the tab indexing of the settings

### PR DESCRIPTION
**Pull request by Karadaliev**
* Fixed the identical tabindexes, and move to a more convenient numbering system
* Moved the Quick Folders button next to the system ones, because its a system one (no popup, etc.)

### CODE REVIEW

**Comment by javihernandez** [comment]
ok to test

**Comment by Karadaliev** [comment]
Can we try to run the tests once more? Because they should work @javihernandez .

**Comment by javihernandez** [comment]
ok to test

**Comment by Karadaliev** [comment]
@javihernandez @amb26 the order has been changed (per Gregg's request), please merge this ASAP 😸

**Pull request merged**
