### PR TITLE
HST 2017 pre-merge check

### PR DESCRIPTION
**Pull request by javihernandez**
This is only to see if CI passes before merging https://github.com/GPII/gpii-app/pull/15 and updating references.

### CODE REVIEW

**Comment by javihernandez** [comment]
ok to test

**Comment by gtirloni** [comment]
After the VM is provisioned, **Windows Update** starts working. That causes the disk to be at 90% utilization (which is worse then CPU/memory being used). While Windows Update is running, the tests fail for me ("User with token os_win7 has no active session").

After I let Windows Update finish, running the tests also fail but with different errors, all related to journal restoration ("Restoration of bad journal file doesn't jam system" - Message: Received correct journal time in journal list markup - at sequence position 13 of 15").

Rebooting the machine (and waiting for the update process to finish), the tests got stuck for 10min at:

```
10:54:16.092:  Invoking handler gpii.deviceReporter.handlers.get for route /device with expectedGrade kettle.request.http
10:54:16.108:  Kettle server allocated request object with type gpii.deviceReporter.handlers.get
```
I killed them after 12min. Reboot the VM once again and it finishes the tests but fails at these:

```
11:09:19.061:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Journal state and restoration" - Message: Received correct journal time in journal list markup - at sequence position 13 of 27
11:09:42.635:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Journal state and restoration" - Message: Received correct journal time in journal list markup - at sequence position 25 of 27
11:10:04.740:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Restoration of bad journal file doesn't jam system" - Message: Received correct journal time in journal list markup - at sequence position 13 of 15
11:09:19.061:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Journal state and restoration" - Message: Received correct journal time in journal list markup - at sequence position 13 of 27
11:09:42.635:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Journal state and restoration" - Message: Received correct journal time in journal list markup - at sequence position 25 of 27
11:10:04.740:  jq: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Restoration of bad journal file doesn't jam system" - Message: Received correct journal time in journal list markup - at sequence position 13 of 15
```

**Comment by amb26** [comment]
Any of the journal failures mean that the system is still running slow. The timeout for those tests is 4 seconds - that is, the system must get to the point of opening the user's session within 4 seconds of receiving the logon. If you look in the logs around the FAIL message you will see some time window messages like this one (from the recent failed run 57):
```
11:13:44.667:  Parsed link date 2017-08-09T18:13:23.151Z to time 1502302403151 expected to be in range [1502302376807, 1502302380807]
```
In this case the logon has taken 24 seconds which is pretty unacceptable - in all of our local testing this stage tages about 1 second.

**Comment by amb26** [comment]
Is it possible that the high resource utilisation is something due to the cost of logging, displaying or transmitting logs?
I can't see where in CI that it is configured how the tests are actually run - could you show me? It might be worth trying redirecting them to a file rather than to the console, if they are not redirected already.

**Comment by amatas** [comment]
I've launched the tests with and without logging to the console on my own desktop PC. The first test is launched using the same command that the CI runs:

$ time vagrant winrm -c 'do.ps1 -c '\''npm test'\'''

```
15:08:17.340:  jq: Test concluded - Module "gpii.contextManager.evaluateMatch tests" Test name "Basic test": 1/1 passed - PASS                                 
15:08:17.355:  jq: ***************     
15:08:17.355:  jq: All tests concluded: 1124/1127 total passed in 566897ms - FAIL                                                                              
15:08:17.355:  jq: ***************     
15:08:17.355:  A total of 1127 tests run, with 3 failed tests. Exiting process with status 3                                                                   
npm ERR! Test failed.  See above for more details.                             


Time:
real    9m43,805s                      
user    4m48,503s                      
sys     0m42,981s           
```           
The following command redirects the output to a text file:

$ time vagrant winrm -c 'do.ps1 -c '\''npm test > output.txt'\'''
```

Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x86

Copyright (C) Microsoft Corporation.  All rights reserved.

Time:
real    7m12,374s
user    0m1,459s
sys     0m0,396s

$ tail output.txt 

15:15:47.942:  jq: Test concluded - Module "OntologyHandlerTests" Test name "gpii.ontologyHandler.prefsToOntology tests": 13/13 passed - PASS
15:15:47.958:  jq: Test concluded - Module "OntologyHandlerTests" Test name "gpii.ontologyHandler.rawPrefsToOntology tests": 6/6 passed - PASS
15:15:48.004:  Successfully queued test Basic test
15:15:48.004:  jq: Test concluded - Module "OntologyHandlerTests" Test name "gpii.ontologyHandler.addPrefsToRawPrefs tests": 5/5 passed - PASS
15:15:48.004:  Active contexts calculated to be: gpii-default
15:15:48.035:  jq: Test concluded - Module "gpii.contextManager.evaluateMatch tests" Test name "Basic test": 1/1 passed - PASS
15:15:48.035:  jq: ***************
15:15:48.035:  jq: All tests concluded: 1127/1127 total passed in 420461ms - PASS
15:15:48.035:  jq: ***************
15:15:48.035:  A total of 1127 tests run, with 0 failed tests. Exiting process with status 0
```
As you can see, the all the tests run faster and also pass.

So I guess that [this line](https://github.com/GPII/ci-service/blob/master/jenkins_jobs/gpii-app.yml#L66) could be changed to:

`vagrant winrm -c "do.ps1 -c 'npm test > output.txt & Get-Content output.txt'"`

But after this change is applied we need to check that a failure in the tests is reflected a the CI, just to be sure that any error is propagated through the rest of the commands.

**Comment by gtirloni** [comment]
@amatas, redirecting to a text file is how I've run all my tests here and they still fail.

**Comment by gtirloni** [comment]
I've executed the test and monitored all processes using Procmon.exe, here's my analysis:

```
Message: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Journal state and restoration" - Message: Received correct journal time in journal list markup - at sequence position 13 of 27
Expected lower: 1502317549316 (10:25:49.316)
Expected upper: 1502317553316 (10:25:53.316)
Time:           1502317557098 (10:25:57.098)
Analysis: VM goes silent (no logs) for 2-second, happening 2-3 times which would account for the issue.


Message: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Journal state and restoration" - Message: Received correct journal time in journal list markup - at sequence position 25 of 27
Expected lower: 1502317569785 (10:26:09.785)
Expected upper: 1502317573785 (10:26:13.785)
Time:           1502317580301 (10:26:20.301)
Analysis: sihost.exe and backgroundTaskHost.exe using disk a lot.

Message: FAIL: Module "gpii.tests.acceptance.windows.builtIn.config tests" Test name "Restoration of bad journal file doesn't jam system" - Message: Received correct journal time in journal list markup - at sequence position 13 of 15
Expected lower: 1502317590973 (10:26:30.973)
Expected upper: 1502317594973 (10:26:34.973)
Time:           1502317601863 (10:26:41.863)
Analysis: VM goes silent (no logs) for 2-second, happening 3-4 times which would account for the issue.
```
This VM was running with VirtualBox Guest Additions 5.1.26 and the time sync set to every 1 second (instead of the default 10 seconds, which might explain >50sec delays).

I don't think we can provide the kind of time assurances in CI with the technology we have. My suggestion would be to relax these time constraints and open a JIRA to research how to best address the issue of performance testing. It might involve a completely different technology stack that can simulate baremetal-like performance inside a VM. VirtualBox is definitely not the solution for that (given all the issues we have had, bad virtual disk performance, etc).

**Comment by amb26** [comment]
OK - thanks for the characteristically thorough investigation of the problems, @gtirloni - since it seems we can't expect any timing characteristics on the CI environment I've relaxed the end requirement to simply be earlier than the present at https://github.com/GPII/universal/pull/538 - @javihernandez , could you push this version back up the stack to here, thanks!

**Comment by javihernandez** [comment]
ok to test

**Comment by javihernandez** [comment]
@amb26 thanks for this last update!
Now that tests are passing, do you want me to merge https://github.com/GPII/universal/pull/538 in? I do know that changes are safe enough and tests are passing but, I was wondering whether you want to perform any other actions related to GPII-2522.

**Comment by amb26** [comment]
Cheers, @jhernandez, yes please merge it all up!

**Comment by javihernandez** [comment]
Now merged, yay!!!
@gtirloni, @amatas, @amb26, thanks for your help! :+1:

**Pull request merged**
