### PR TITLE
GPII-4067: Change Tool Tip for the Reset-To-Standard button

### PR DESCRIPTION
**Pull request by Karadaliev**
* Changed the tooltip of the Reset service button

### CODE REVIEW

**Comment by amb26** [comment]
ok to test

**Comment by Karadaliev** [comment]
@amb26 can you re-test this one, it should pass - the change is just in the tooltip's text 😺

**Comment by amb26** [comment]
@the-t-in-rtf - this looks like that race in collecting coverage data that we sometimes see - 
````
10:35:42.799:  Test case listener has not responded after 5000ms - at sequence pos 11 of 11 sequence element {
    "task": "gpii.tests.app.instrumentedDialog.requestCoverage",
    "resolve": "fluid.log",
    "resolveArgs": "Renderer coverage collected!"
} of fixture GPII application integration tests
10:35:44.893:  RendererCoverage: Report collected: 7gpii.app.qssInWrapper
10:35:44.893:  RendererCoverage: Still awating: [
    "gpii.app.waitDialog",
    "gpii.app.aboutDialog",
    "gpii.app.qssNotification",
    "gpii.app.qssWidget",
    "gpii.app.qssMorePanel",
    "gpii.app.qssTooltipDialog",
    "gpii.app.pspInApp"
]
````

**Comment by amb26** [comment]
ok to test

**Pull request merged**
