### PR TITLE
GPII-3805: Remove "Record screen capture with computer audio+mic" button from Screen Capture menu

### PR DESCRIPTION
**Pull request by krisYanachkov**
Remove "Record screen capture with computer audio+mic" button from Screen Capture menu.

### CODE REVIEW

**Comment by javihernandez** [comment]
ok to test

**Comment by amb26** [comment]
Hi @krisYanachkov - please could you merge up all of your outstanding branches with the new master which was just merged to include all of @the-t-in-rtf 's work repairing the gpii-app test cases to function with CouchDB

**Comment by amb26** [comment]
Failure due to test hang awaiting results of gpii.app.qssNotification

````
05:42:54.762:  RendererCoverage: Report collected: 1gpii.app.errorDialog
05:42:54.762:  RendererCoverage: Still awating: [
    "gpii.app.qssNotification"
]
````

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
The first failure was the "Narrator must no longer be running" failure
````
03:54:53.908:  jq: FAIL: Module "gpii.tests.windows.registeredAT" Test name "Testing real AT" - Message: Narrator must no longer be running
03:54:53.908:  jq: Source:     at pok (\\vboxsvr\vagrant\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:112:15)
````
reported with @stegru  at https://issues.gpii.net/browse/GPII-3303 and possibly https://issues.gpii.net/browse/GPII-3081

**Pull request merged**
