### PR TITLE
GPII-4189, GPII-4190, GPII-4191: My Google Drive, My One Drive, and My Dropbox

### PR DESCRIPTION
**Pull request by Karadaliev**
GPII-4189, GPII-4190, GPII-4191: All three url based buttons (My Google Drive, My One Drive, and My Dropbox) are added

* Added siteConfig variables for all the buttons under qss.urls
* Added ids to be used in the buttonList: "url-google-drive", "url-one-drive", "url-dropbox"
* Added messageBundle variables for the titles and tooltips
* Fixed some linting issues from the previous merges

### CODE REVIEW

**Comment by Karadaliev** [comment]
Hey @amb26 can we test this out and merge it, because contains linting error fixes except for the new buttons. And its quite easy to check out (very simple url buttons) too 🛩 .

**Comment by Karadaliev** [comment]
@amb26 Another reminder to take a short look at this 😸 .

**Comment by Karadaliev** [comment]
@javihernandez can you start the send the message to the bot in order to run the tests 🔹 ?

**Comment by amb26** [comment]
ok to test

**Pull request merged**
