### PR TITLE
GPII-3577: CI pass in advance for 1.0.1

### PR DESCRIPTION
**Pull request by javihernandez**

### CODE REVIEW

**Comment by stegru** [comment]
ok to test

**Comment by javihernandez** [comment]
> CI job passed: https://ci.gpii.net/job/gpii-app-tests/475/

ok, what about a 3rd pass? ok to test

**Comment by stegru** [comment]
It didn't make it to the windows tests, the last thing is:

```
12:36:04.114:  Test case listener has not responded after 5000ms - at sequence pos 3 of 35 sequence element {

    "event": "{testEnvironment}.events.noUserLoggedIn",

    "listener": "fluid.identity"

} of fixture Settings broker integration tests
```

```c
while (fail) { ok to test }
```

**Comment by javihernandez** [comment]
This was not meant to be merged and is no longer required. Will produce a new pr with the most recent master to make 1.0.1 pass on CI.

**Pull request closed without merging**
