### PR TITLE
GPII-2349: Basic implementation of network diagnostic request system for HST

### PR DESCRIPTION
**Pull request by amb26**

### CODE REVIEW

**Comment by michelled** [comment]
@amb26 I wonder about the naming of 'networkTest'. Perhaps 'networkCheck' or 'networkAvailable' would be clearer given the general understanding of the word 'test'.

**Comment by amb26** [comment]
Cheers @michelled , good suggestion - I've updated the pull with "networkCheck"

**Comment by michelled** [comment]
I wonder if we should also rename the file, @amb26

**Comment by amb26** [comment]
Cheers, @michelled - now renamed

**Comment by michelled** [comment]
great - I'll ask @cindyli to merge it.

**Comment by michelled** [comment]
@amb26 could you merge the hst-2017 branch into this pull request? CI should start passing again if you do that

**Comment by amb26** [comment]
I did, but there are a number of linting errors in the hst-2017 branch that we should deal with

**Pull request merged**
