### PR TITLE
AJC3 branch CI pass

### PR DESCRIPTION
**Pull request by javihernandez**

### CODE REVIEW

**Comment by javihernandez** [comment]
@georgitodorov @danailbd, this is in sync with your feature/QSS1.1 branch, the only difference is that I've updated the windows reference to use the ajc3 branch of windows (which is current master but without the node10 update nor the ffi replacement). Can you take a look at these CI failures?

**Comment by stegru** [comment]
> CI job passed: https://ci.gpii.net/job/gpii-app-tests/372/

Wow, it passed? CI must be broke

**Comment by javihernandez** [comment]
> CI job passed: https://ci.gpii.net/job/gpii-app-tests/384/

Now, with the installer creation re-enabled:

```
This run spent:
  22 min waiting;
  46 min build duration;
  1 hr 9 min total from scheduled to completion.
```

**Comment by javihernandez** [comment]
Closing since this is not being used anymore

**Pull request closed without merging**
