### PR TITLE
GPII-3713: Keyed out message moved to the site config

### PR DESCRIPTION
**Pull request by krisYanachkov**

### CODE REVIEW

**Comment by javihernandez** [comment]
ok to test

**Comment by amb26** [comment]
This has encountered some kind of genuine failure resulting from a race condition, unrelated to the issue of the pull:
````
05:01:04.609:  FATAL ERROR: Uncaught exception: Cannot read property 'keyedOut' of undefined

TypeError: Cannot read property 'keyedOut' of undefined
    at gpii.app.qssWrapper.saveSettings (\\vboxsvr\vagrant\instrumented\src\main\qss.js:1:28548)
````

**Comment by amb26** [comment]
Ah sorry, the failure is directly related to the issue of the pull :)

**Comment by Karadaliev** [comment]
Hey @amb26 this PR is ready to be re-reviewed 😄

**Pull request merged**
