### PR TITLE
GPII-2514: Removed 'Exit' from the menu in production mode

### PR DESCRIPTION
**Pull request by michelled**

### CODE REVIEW

**Comment by kaspermarkus** [comment]
ok to test

**Comment by kaspermarkus** [comment]
@amb26 @michelled @gtirloni I've tried running the tests on my local VM and they all pass... Is there a known issue with them not running on CI? Seems like a socket hang up and timeout - also I saw something in last weeks arch meeting notes related to GPII app and things being really slow

**Comment by gtirloni** [comment]
@kaspermarkus yes, see https://github.com/GPII/gpii-app/pull/19

**Comment by kaspermarkus** [comment]
@michelled could you merge this with the latest HEAD of hst-2017 -- that should get the tests to pass so I can merge it!

**Comment by kaspermarkus** [comment]
and thanks for the answer @gtirloni

**Comment by michelled** [comment]
@kaspermarkus I merged in the hst branch - this is ready for you :)

**Comment by kaspermarkus** [comment]
Great - thanks @michelled! Tested and everything works as it should!

**Pull request merged**
