### PR TITLE
GPII-4196: Create the new More panel

### PR DESCRIPTION
**Pull request by Karadaliev**
**More Panel is created with all of the required basic functions as follows:**

* New service button to open the More panel;
* New styles for the QSS and the More Panel (that shows above it);
* New panel (well, the More Panel) with grid-style button layout that you can put any desired button from the buttonList there, even the custom buttons;
* From a usability standpoint the More Panel works properly even changing the DPI level, or not filling properly the morePanelList data, it will auto-fill the grid with empty elements when needs to;
* Also we handle the widget window's position based on the position of the button now, so if the widget gets too close to the right part of the screen it will still fit and the arrow will show over the appropriate button;
* For the widget's sideCar we made similar arrangements (and according to the original sideCar specs as well), we make sure that the sideCar will be visible no matter where the button is, even to the extend to show the sideCar on the LEFT of the widget window if there is no space on the right.

**Usage Information:**

* The options for the More Panel grid are in siteConfig > morePanelOptions node
* The buttons that will show in the grid are in siteConfig > morePanelList. It uses a simple array structure, one element for one row (by default 3 rows, so 3 lists)
* The link and the both button blocks are HTML code that can be changed freely using the message bundles: "gpii_qss_list_infoBlock", "gpii_qss_list_buttonBlock1", "gpii_qss_list_buttonBlock2"

**IMPORTANT:**
This is fully functional version of the More Panel witch covers GPII-4337, GPII-4274, GPII-4313, and parts of GPII-4337 (the too close to the right scenario). It's great base for testing and the review process and can be used for demo purposes. Still **keep in mind** that not all of the specs are covered, and none of the links (and buttons) in the More Panel's headers lead to anywhere (this can be changed to go to certain web sites as mentioned above). I also **recommend** this to be used in the current 10x3 grid and to have at-least 8 buttons in the main QSS panel.

### CODE REVIEW

**Comment by amb26** [comment]
ok to test

**Comment by amb26** [comment]
@Karadaliev - we would appreciate any help with understanding the current CI hangs, which are affecting pulls such as https://github.com/GPII/gpii-app/pull/178 and https://github.com/GPII/gpii-app/pull/182 - we have not had a successful CI run for gpii-app for nearly 2 weeks

**Comment by Karadaliev** [comment]
Ready for review (and possible a merge?!) 🛩️

**Comment by javihernandez** [comment]
@danailbd can you update it with current master?

**Comment by Karadaliev** [comment]
Done, merged with master. Ready for review and/or merge @amb26 🛩️

**Pull request merged**
