### PR TITLE
GPII-2915: Add code coverage reporting.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-2915](https://issues.gpii.net/browse/GPII-2915) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
Please note, the new "coverage" command does not currently work in a windows VM.  The tests always hang at a particular point.  The ASTEA team suggested they might be able to help review, I am committing what I have to assist with that.

To run the coverage report:

1. Check out [this branch](https://github.com/the-t-in-rtf/gpii-app/tree/GPII-2915).
2. Create a Vagrant VM using `vagrant destroy -f` and `vagrant up`.
3. Open a powershell window in the VM and change to the `v:` directory.
4. Run `npm install` and then `npm coverage`.

In my testing, only `npm test` works, I can never get the instrumented tests to complete.

**Comment by the-t-in-rtf** [comment]
Someone at ASTEA offered to review in a recent architecture meeting:

https://pad.gpii.net/p/arch-2018-03-28-cx74n0f

@georgitodorov, do you know who offered that?  I would love some help here.

**Comment by the-t-in-rtf** [comment]
Thanks to @georgitodorov for narrowing things down to the integration tests.  By commenting out various tests in that file, I narrowed it down one of the following:

```
    //fluid.copy(gpii.tests.dialogManager.testDefs), // NOT OK
    //fluid.copy(gpii.tests.sequentialDialogs.testDefs), // NOT OK
    //fluid.copy(gpii.tests.webview.testDefs) // NOT OK
```

**Comment by georgitodorov** [comment]
Whenever test coverage is calculated, the code of the application is copied to a directory named `instrumented`. However, the `node_modules` are left in the main folder. The various renderer components of the PSP make references to some files from the `gpii-universal` node module and these references are relative paths. When the code is copied to the `instrumented` folder, one more level of nesting is introduced and these relative paths are no longer pointing to a valid location in the file system. A possible quick solution will be to copy not only the code that will be tested but also the `node_modules` (or, for simplicity and speed, only the `gpii-universal` module).

**Comment by the-t-in-rtf** [comment]
Thanks for the key insight, @georgitodorov.  I did a thorough search for the files included via relative include from HTML fixtures and copied those to the instrumented directory so that the relative paths would be correct.   There is now an `npm run coverage` command that should run the instrumented tests and generate a report.

I get errors in a Vagrant VM where the script does not complete successfully, but it seems to happen late enough that the coverage is collected successfully.  By manually running `npm run postcoverage`, I was able to generate the following report earlier.

http://the-t-in-rtf.github.io/coverage-reports/gpii-app/201804190948/

In later review, I ran across tests I had commented out earlier in trying to track down the problem, so this is likely not quite complete.  I updated most dependencies, now I get a failure like the following:

```
05:34:30.940:  Creating GPII settings directory in C:\Users\vagrant\AppData\Roaming/gpii
TypeError: Invalid template for Menu
    at Function.Menu.buildFromTemplate (V:\node_modules\electron\dist\resources\electron.asar\browser\api\menu.js:171:11
)
    at gpii.app.updateMenu (V:\src\main\menu.js:70:30)
```

Not sure what's going on, perhaps I need to revert the change in the electron version?

**Comment by danailbd** [comment]
For this electron error, you can take a look at this PR https://github.com/GPII/gpii-app/pull/45

**Comment by the-t-in-rtf** [comment]
Good news!  Now that I reverted to previous Electron versions, the tests and coverage now run consistently in Vagrant.  With all tests running, the coverage is much better:

https://the-t-in-rtf.github.io/coverage-reports/gpii-app/201804192014/

@amb26, this should be ready for review.

**Comment by the-t-in-rtf** [comment]
The latest CI failure seems like a timeout provisioning the VM.  OK to test again.

**Comment by amb26** [comment]
The branch seems to work but all of the fluid.log output is missing, as well as the output from jqUnit, which makes it impossible to tell whether the tests have passed. Here is some sample middle output from the run: 
```
Error removing temporary directory: Rimraf failed to complete within 1000 milliseconds...
Error
Error removing temporary directory: Rimraf failed to complete within 1000 milliseconds...
undefined
Error removing temporary directory: Rimraf failed to complete within 1000 milliseconds...
undefined
Error removing temporary directory: Rimraf failed to complete within 1000 milliseconds...
(node:6744) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Error removing temporary directory: Rimraf failed to complete within 1000 milliseconds...
undefined
Error removing temporary directory: Rimraf failed to complete within 1000 milliseconds...
```
It would be interesting to know what it is that logs "undefined" so often, and I also worry about the constant rimraf failures, but primarily we need the primary console output of the tests back.

I've made a "merge branch" of my own to update this branch to master which may save you some time:
https://github.com/amb26/gpii-app/tree/GPII-2915

The behaviour is the same as with this one.

**Comment by the-t-in-rtf** [comment]
I will see what I can do about the logging output.  I could use help tracking down the `undefined` messages.  I can only run the tests in a VM, and debugging is harder than it should be there.

**Comment by the-t-in-rtf** [comment]
At least some of the `undefined` messages are likely down to this bug I discovered in gpii-testem:

https://issues.gpii.net/browse/GPII-2993

**Comment by the-t-in-rtf** [comment]
Ok to test again.

**Comment by amb26** [comment]
I tried out this branch and still got no useful console output as well as continued "undefined" notifications. I did test with what looks like the recent gpii-testem build referenced in this pull version 2.1.1-dev.20180507T130130Z.861e618

**Comment by the-t-in-rtf** [comment]
Thinking it through further, I had to remind myself that a) this package doesn't use gpii-testem to run its tests and b) the faulty error output occurs with the non-coverage test commands.  I suspect the rimraf errors are still coming from gpii-testem, but they'd have to be a result of running the universal and/or windows tests.  I am testing changes locally to see if I can reduce the number of timeouts, I may need to put in a couple of small pulls against those depending.  I also have ideas about narrowing down both problems by selectively running only some of the tests.  This is likely to be a longer effort in the background, I will report back when I have something to report.

**Comment by the-t-in-rtf** [comment]
The rimraf timeouts are coming from tests that use gpii-pouchdb.  Even increasing the timeout to 10 seconds doesn't avoid the problem.  That package already uses the latest graceful-fs, I'm not sure what else we can do to mitigate this.

**Comment by the-t-in-rtf** [comment]
The log output is hidden by this bit of monkey-patching:

https://github.com/GPII/gpii-app/blob/master/src/main/logging.js#L30

@amb26 and others, we should discuss the rationale for that and figure out a way to make this optional.

**Comment by the-t-in-rtf** [comment]
@amb26 and others, just to confirm, as far as I can see all of the reported problems with the output have now been addressed.  There are a few lingering `undefined` messages, but I see no timeouts and the test output is visible again.

**Comment by amb26** [comment]
Thanks, @the-t-in-rtf - I was able to run the tests successfully with suitable console output. Should we not set up the scripts so that tests automatically produce coverage as we do with other projects?

**Comment by amb26** [comment]
OK, sorry to say that now I actually try to execute "npm run coverage", although the overall test run is a success, the run terminates with the following error:
```
> node node_modules/nyc/bin/nyc.js report

\\vboxsvr\vagrant\node_modules\nyc\node_modules\yargs\yargs.js:1133
      else throw err
           ^

Error: ENOENT: no such file or directory, scandir 'C:\vagrant\coverage'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at NYC.eachReport (\\vboxsvr\vagrant\node_modules\nyc\index.js:526:31)
    at NYC._getCoverageMapFromAllCoverageFiles (\\vboxsvr\vagrant\node_modules\nyc\index.js:428:8)
    at NYC.report (\\vboxsvr\vagrant\node_modules\nyc\index.js:446:18)
    at Object.exports.handler (\\vboxsvr\vagrant\node_modules\nyc\lib\commands\report.js:44:7)
    at Object.runCommand (\\vboxsvr\vagrant\node_modules\nyc\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (\\vboxsvr\vagrant\node_modules\nyc\node_modules\yargs\yargs.js:1046:30)
    at Object.parse (\\vboxsvr\vagrant\node_modules\nyc\node_modules\yargs\yargs.js:551:25)
    at Object.<anonymous> (\\vboxsvr\vagrant\node_modules\nyc\bin\nyc.js:24:35)

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "coverage"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! gpii-app@0.3.0 postcoverage: `node node_modules/nyc/bin/nyc.js report`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gpii-app@0.3.0 postcoverage script 'node node_modules/nyc/bin/nyc.js report'.
```

**Comment by the-t-in-rtf** [comment]
@amb26, @georgitodorov reported something similar in IRC, I'm looking at it now and will report back.

**Comment by the-t-in-rtf** [comment]
OK, I committed a fix, @amb26 @georgitodorov, you should be able to pull the changes and run `npm run coverage` now.

**Comment by the-t-in-rtf** [comment]
Per discussions with @amb26, I have made the coverage run now run when `npm test` is called.  I updated the docs to indicate how to run the tests without coverage, which you can do with a new script, `npm run test:noCoverage`.

**Comment by the-t-in-rtf** [comment]
Just a quick status report.  The builds run, the coverage report runs, but it's empty.  I will look into it on Monday.

**Comment by the-t-in-rtf** [comment]
I added additional cleanup steps just to make sure that my local results were not a result of data from previous runs, and moved the build step before instrumentation.  I then verified that a full run in a fresh VM results in coverage data.  Looking at the console output from previous runs, it claims to have saved coverage data, so I'm really not sure what's going on here.  I'm running a CI build with the latest commits to see if either of those helped.

**Comment by amb26** [comment]
The "object has been destroyed" messages are always a red herring since they are just diagnostics we receive after the test run has finished. In fact there was a genuine test failure
```
11:41:04.849:  jq: FAIL: Module "Windows Display Settings Handler Tests" Test name "Testing setScreenDpi " - Message: setScreenDpi 120%
11:41:04.894:  jq: Expected: {
    "actual": 1.25,
    "configured": 1.25,
    "maximum": 1.25
}
11:41:04.946:  jq: Actual: {
    "configured": 1.25,
    "maximum": 1,
    "actual": 1
}
```
Which may be some kind of genuine though regrettable intermittent test failure. I'll kick off a run locally as well for good measure and see what we're receiving for coverage data.

**Comment by amb26** [comment]
Well, for me the tests pass, but still zero coverage data

**Comment by amb26** [comment]
This time I did get the diagnostic:
````
02:48:24.601:  jq: ***************
02:48:24.606:  Error saving coverage data:{
    "errno": -4071,
    "code": "EINVAL",
    "syscall": "open",
    "path": "\\\\vboxsvr\\vagrant\\coverage\\coverage-tests-2018-05-18T09:48:24.602Z.json"
}
````

**Comment by amb26** [comment]
Which is true - the "coverage" directory is empty

**Comment by the-t-in-rtf** [comment]
If you change `fs = require("graceful-fs")` to `fs = require("fs")`, does it make a difference?

**Comment by the-t-in-rtf** [comment]
In `tests.js`, I mean.

**Comment by the-t-in-rtf** [comment]
Ah, great, thanks, just saw the coverage saving failure.

**Comment by the-t-in-rtf** [comment]
[The last build](https://ci.gpii.net/job/gpii-app-tests/239/) passed, although it was a few commits back and passed without coverage using `fs`.  The build claims that coverage data was saved, now waiting on the latest build which should at least give us an idea of *how much* coverage data was saved.

**Comment by the-t-in-rtf** [comment]
OK, I know exactly what's going on:

```
> gpii-app@0.3.0 posttest C:\vagrant
> node node_modules/nyc/bin/nyc.js report --temp-directory coverage


=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
PS C:\vagrant> v:
PS V:\> npm run posttest

> gpii-app@0.3.0 posttest V:\
> node node_modules/nyc/bin/nyc.js report --temp-directory coverage


=============================== Coverage summary ===============================
Statements   : 88.63% ( 639/721 )
Branches     : 70.17% ( 127/181 )
Functions    : 83.52% ( 147/176 )
Lines        : 88.63% ( 639/721 )
================================================================================
```

The coverage report will run from v:, but not from c:/vagrant.  I have entered a ticket for the devops team [here](https://issues.gpii.net/browse/GPII-3055).

**Comment by amatas** [comment]
ok to test

**Comment by the-t-in-rtf** [comment]
@amb26, the coverage report will never run successfully in CI until the configuration is updated to run commands from v: instead of c:/vagrant.  I have put in a ticket with the devops team, @amatas or someone else one the devops team, please comment.

**Comment by the-t-in-rtf** [comment]
OK to test again.

**Comment by the-t-in-rtf** [comment]
Alfredo updated the CI config since the last build started.  Ok to test again.

**Comment by amatas** [comment]
I've checked out this PR on my PC and I got the same errors as the CI either if I run the tests from `c:\vagrant` or `v:`:
```

    at sendToEmbedder (\\vboxsvr\vagrant\node_modules\electron\dist\resources\electron.asar\browser\guest-view-manager.js:123:16)

    at WebContents.<anonymous> (\\vboxsvr\vagrant\node_modules\electron\dist\resources\electron.asar\browser\guest-view-manager.js:130:7)

    at emitOne (events.js:120:20)

    at WebContents.emit (events.js:210:7)

05:11:56.616:  FATAL ERROR: Uncaught exception: Object has been destroyed

Error: Object has been destroyed

    at WebContents.send (\\vboxsvr\vagrant\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:97:15)

    at sendToEmbedder (\\vboxsvr\vagrant\node_modules\electron\dist\resources\electron.asar\browser\guest-view-manager.js:123:16)

    at WebContents.<anonymous> (\\vboxsvr\vagrant\node_modules\electron\dist\resources\electron.asar\browser\guest-view-manager.js:130:7)

    at emitOne (events.js:120:20)

    at WebContents.emit (events.js:210:7)

05:11:56.617:  Current activity: 

05:11:56.622:  {

    "module": "GPII",

    "event": "Error.Exception",

    "level": "FAIL",

    "data": {

        "error": {

            "stack": "Error: Object has been destroyed\n    at WebContents.send (\\\\vboxsvr\\vagrant\\node_modules\\electron\\dist\\resources\\electron.asar\\browser\\api\\web-contents.js:97:15)\n    at sendToEmbedder (\\\\vboxsvr\\vagrant\\node_modules\\electron\\dist\\resources\\electron.asar\\browser\\guest-view-manager.js:123:16)\n    at WebContents.<anonymous> (\\\\vboxsvr\\vagrant\\node_modules\\electron\\dist\\resources\\electron.asar\\browser\\guest-view-manager.js:130:7)\n    at emitOne (events.js:120:20)\n    at WebContents.emit (events.js:210:7)",

            "message": "Object has been destroyed"

        }

    }

}

05:11:56.626:  FATAL ERROR: Uncaught exception: Object has been destroyed

Error: Object has been destroyed

    at WebContents.send (\\vboxsvr\vagrant\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:97:15)

    at sendToEmbedder (\\vboxsvr\vagrant\node_modules\electron\dist\resources\electron.asar\browser\guest-view-manager.js:123:16)

    at WebContents.<anonymous> (\\vboxsvr\vagrant\node_modules\electron\dist\resources\electron.asar\browser\guest-view-manager.js:130:7)

    at emitOne (events.js:120:20)

    at WebContents.emit (events.js:210:7)


> gpii-app@0.3.0 posttest C:\vagrant
> node node_modules/nyc/bin/nyc.js report --temp-directory coverage


=============================== Coverage summary ===============================
Statements   : 88.63% ( 639/721 )
Branches     : 70.17% ( 127/181 )
Functions    : 83.52% ( 147/176 )
Lines        : 88.63% ( 639/721 )
================================================================================
```

Running the tests from V: instead of c:\Vagrant

```
06:28:20.497:  FATAL ERROR: Uncaught exception: Object has been destroyed

Error: Object has been destroyed

    at WebContents.send (V:\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:97:15)

    at sendToEmbedder (V:\node_modules\electron\dist\resources\electron.asar\browser\guest-view-manager.js:123:16)

    at WebContents.<anonymous> (V:\node_modules\electron\dist\resources\electron.asar\browser\guest-view-manager.js:130:7)

    at emitOne (events.js:120:20)

    at WebContents.emit (events.js:210:7)

06:28:20.499:  Current activity: 

06:28:20.503:  {

    "module": "GPII",

    "event": "Error.Exception",

    "level": "FAIL",

    "data": {

        "error": {

            "stack": "Error: Object has been destroyed\n    at WebContents.send (V:\\node_modules\\electron\\dist\\resources\\electron.asar\\browser\\api\\web-contents.js:97:15)\n    at sendToEmbedder (V:\\node_modules\\electron\\dist\\resources\\electron.asar\\browser\\guest-view-manager.js:123:16)\n    at WebContents.<anonymous> (V:\\node_modules\\electron\\dist\\resources\\electron.asar\\browser\\guest-view-manager.js:130:7)\n    at emitOne (events.js:120:20)\n    at WebContents.emit (events.js:210:7)",

            "message": "Object has been destroyed"

        }

    }

}

06:28:20.505:  FATAL ERROR: Uncaught exception: Object has been destroyed

Error: Object has been destroyed

    at WebContents.send (V:\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:97:15)

    at sendToEmbedder (V:\node_modules\electron\dist\resources\electron.asar\browser\guest-view-manager.js:123:16)

    at WebContents.<anonymous> (V:\node_modules\electron\dist\resources\electron.asar\browser\guest-view-manager.js:130:7)

    at emitOne (events.js:120:20)

    at WebContents.emit (events.js:210:7)


> gpii-app@0.3.0 posttest V:\
> node node_modules/nyc/bin/nyc.js report --temp-directory coverage


=============================== Coverage summary ===============================
Statements   : 88.63% ( 639/721 )
Branches     : 70.17% ( 127/181 )
Functions    : 83.52% ( 147/176 )
Lines        : 88.63% ( 639/721 )
================================================================================
```

**Comment by amb26** [comment]
@amatas - those are not errors, due to an electron bug every test run finishes with that kind of transcript. The fact that you get coverage data proves that the run was successful on your machine. The real test run status appears few hundred lines higher up in the transcript with material like
```
02:08:19.715:  jq: ***************
02:08:19.715:  jq: All tests concluded: 2217/2217 total passed in 746592ms - PASS
02:08:19.715:  jq: ***************
```

Do you think you could try one or more of the fixes suggested on the JIRA by @stegru to see whether they fix CI?
Also, is there some way to get the console output from Jenkins converted to UNIX format so we don't have to remove all the blank lines from it manually?

**Comment by stegru** [comment]
ok to test

**Pull request merged**
