### PR TITLE
GPII-4104: New spacer button

### PR DESCRIPTION
**Pull request by Karadaliev**
Added the non-functional separator type button, basic usage - in siteConfig.json in the buttonList array use "_separator_" as ID for the invisible type, and "_separator-visible_" for the visible one.

**Example:**
`buttonList: [
    "language",
    "translate-tools",
    "separator",
    "screen-zoom",
    "text-zoom",
    "separator",
    "screen-capture",
    "office-simplification",
    "high-contrast",
    "read-aloud",
    "volume",
    "separator",
    "launch-documorph",
    "cloud-folder-open",
    "usb-open",
    "separator-visible",
    "service-more",
    "service-save",
    "service-undo",
    "service-dummy",
    "service-reset-all",
    "service-close"
]`

### CODE REVIEW

**Comment by cindyli** [comment]
ok to test

**Comment by amb26** [comment]
Please can you try updating to latest gpii-windows release 0.3.0-dev.20190917T132958Z.ba98a5a which should include @stegru 's work on office simpliciation as well as some other fixes

**Comment by Karadaliev** [comment]
> Please can you try updating to latest gpii-windows release 0.3.0-dev.20190917T132958Z.ba98a5a which should include @stegru 's work on office simpliciation as well as some other fixes

Sure, its updated now.

**Comment by Karadaliev** [comment]
@amb26 can we retest this, seems like the test died for some "network failure" reason 🛩

**Comment by amb26** [comment]
ok to test

**Pull request merged**
